name = "CHSH_Test"
uuid = "936a3a7a-f784-4ee0-887c-27a1b4c296dc"
authors = ["itsdfish <itsdfish@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
